global:
  scrape_interval: 1s
  scrape_timeout: 1s
  external_labels:
    stack: inferstack
  evaluation_interval: 1s
rule_files:
- rules/*.yml
scrape_configs:
- job_name: inferstack-gateway
  metrics_path: /metrics
  static_configs:
  - targets:
    - 127.0.0.1:18080
    labels:
      component: gateway
- job_name: vllm
  metrics_path: /metrics
  static_configs:
  - targets:
    - 127.0.0.1:18000
    labels:
      component: engine
- job_name: prometheus
  static_configs:
  - targets:
    - 127.0.0.1:19090
